### ISSUE TITLE
Wrenches published by PR2 F/T sensor do not have frame-id

### ISSUE THREAD

**Issue by airballking** [PR2/pr2_ethercat_drivers#66]
This makes it difficult to visualize the f/t measurements in rviz.

Also, the urdf has two frames related to the f/t sensor after updating the pr2 urdf (with the scripts from pr2_ft). It feels like an educated-guessing game to chose the right frame w.r.t. which calculations should interpret the measurements. A clarification should help avoid mistakes for all users.

Would it break the real-time loop to have this added to the header of the published messages?

**Comment by UltronDestroyer** [comment]
Hmm, what are the frames? raw_ft, ft?

If that's the case then it's always assumed that the raw_ft is the one directly from the sensor and _not_ ready for measurements yet.

**Comment by airballking** [comment]
After `robot start` on the PR2, I enter `rostopic echo /ft/l_gripper_motor` for the f/t sensor installed on the left arm of the robot. Messages like this one are going over the topic:

```
header: 
  seq: 210285
  stamp: 
    secs: 1402902576
    nsecs: 560354396
  frame_id: ''
wrench: 
  force: 
    x: 0.351951055023
    y: -14.4350184399
    z: 24.7228982002
  torque: 
    x: -0.807430490576
    y: -0.73970471998
    z: -0.0113289632462
```
